insert into mywebapp_db.my_table_object (user_id,user_name, phone) values(0,'Abdul Kareem', '872-222-3435'); 
insert into mywebapp_db.my_table_object (user_id,user_name, phone) values(0,'Waqas', '872-234-567'); 
insert into mywebapp_db.my_table_object (user_id,user_name, phone) values(0,'Sohail', '872-220-000'); 
insert into mywebapp_db.my_table_object (user_id,user_name, phone) values(0,'John', '872-242-234'); 
insert into mywebapp_db.my_table_object (user_id,user_name, phone) values(0,'Smith', '872-224-567'); 
insert into mywebapp_db.my_table_object (user_id,user_name, phone) values(0,'Thomas', '872-224-678'); 
insert into mywebapp_db.my_table_object (user_id,user_name, phone) values(0,'Amina', '872-228-765'); 
insert into mywebapp_db.my_table_object (user_id,user_name, phone) values(0,'Saira', '872-223-543'); 
insert into mywebapp_db.my_table_object (user_id,user_name, phone) values(0,'Tom Smith', '872-222-452'); 
insert into mywebapp_db.my_table_object (user_id,user_name, phone) values(0,'Jonse', '872-222-689'); 
insert into mywebapp_db.my_table_object (user_id,user_name, phone) values(0,'Richard James', '872-223-125'); 
insert into mywebapp_db.my_table_object (user_id,user_name, phone) values(0,'David', '872-224-098'); 
insert into mywebapp_db.my_table_object (user_id,user_name, phone) values(0,'Arnold', '872-220-890'); 
